#system window full screen
settings:
  debug: "on"
  #debug: "off"

  #dictionary: "/home/henrikbeck95/Desktop/tcc/voice_assistant_linux/src/dictionary.txt"
  dictionary: "/home/henrikbeck95/Desktop/tcc/voice_assistant_linux/src"
  
  training:
    #mode: "on"
    mode: "off"
    word: "software"
    #word: "system"
    #word: ""

  language: "en-US"
  #language: "pt-BR"
  speech_speed: "low"
  #speech_speed: "normal"
  #speech_speed: "fast"
  #speech_volume: "low"
  speech_volume: "normal"
  #speech_volume: "high"
software:
  firefox: "firefox &"
  menu: "$HOME/.dotfiles/scripts/rofi_launcher.sh --rofi-theme-launchpad &"
  nautilus: "nautilus &"
  spotify: "spotify &"
  #terminal: "exec i3-sensible-terminal &"
  terminal: "konsole &"
system:
  brightness:
    up: "$HOME/.dotfiles/scripts/system_brightness.sh --max"
    #up: "echo 937 > /sys/class/backlight/intel_backlight/brightness"
    down: "$HOME/.dotfiles/scripts/system_brightness.sh --min"
  volume:
    up: "$HOME/.dotfiles/scripts/system_dbus_player.sh --system-volume-up"
    down: "$HOME/.dotfiles/scripts/system_dbus_player.sh --system-volume-down"
  #config:
  #  reload: "i3 reload"
  #  restart: "i3 restart"
  window:
    close: "i3 kill"
    floating: "i3 floating toggle"
    full_screen: "i3 fullscreen toggle"
    stick: "i3 sticky toggle"
    focus:
      up: "i3 focus up"
      left: "i3 focus left"
      right: "i3 focus right"
      down: "i3 focus down"
    move:
      up: "i3 move up"
      left: "i3 move left"
      right: "i3 move right"
      down: "i3 move down"
  workspace:
    go:
      last: "i3 workspace back_and_forth"
      number: "i3 workspace number $wsHome"
      next: "i3 workspace next"
      prev: "i3 workspace prev"
    move:
      last: "i3 move container to workspace back_and_forth"
      number: "i3 move container to workspace number $wsHome"
      next: "i3 move container to workspace next"
      prev: "i3 move container to workspace prev"
user:
  file_recording: "/tmp/val_voice_user.wav"
val:
  message_error_command_not_listed: "Command could not be detected"
  #message_error_microphone: "An error has occurred. Your microphone device might not be correctly configured. Please, check it out before try again."
  message_error_microphone: "An error has occurred. Your microphone device might not be correctly configured or there is no internet connection. Please, check it out before try again."
  message_introduction: "How can I help you!?"
  message_success_command_listed: "Command has been validated!"
  message_running: "VAL is listening..."
  message_welcome: "Val here!"
  #message_welcome: "Estou tentando entender a sua fala..."